import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Menu_Utama extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Utama
     */
    public Menu_Utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        kndraanMasuk = new javax.swing.JButton();
        kndraanKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jexit = new javax.swing.JButton();

        exit.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Pictures\\building-infrastructure-station-concrete.jpg")); // NOI18N
        exit.setText("Exit");
        exit.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        kndraanMasuk.setText("kendaraan Masuk");
        kndraanMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kndraanMasukActionPerformed(evt);
            }
        });
        getContentPane().add(kndraanMasuk);
        kndraanMasuk.setBounds(190, 150, 215, 55);

        kndraanKeluar.setText("kendaran Keluar");
        kndraanKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kndraanKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(kndraanKeluar);
        kndraanKeluar.setBounds(190, 240, 215, 54);

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel1.setText("Menu parkiran Siskom");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 50, 270, 40);

        jexit.setText("Exit");
        jexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexitActionPerformed(evt);
            }
        });
        getContentPane().add(jexit);
        jexit.setBounds(250, 360, 51, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kndraanMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kndraanMasukActionPerformed
        // TODO add your handling code here:
        new kendaraanMasuk().setVisible(true);
        JOptionPane.showMessageDialog(null, "Selamat Datang" , "Menu Utama" , JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_kndraanMasukActionPerformed

    private void kndraanKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kndraanKeluarActionPerformed
        // TODO add your handling code here:
        new kendaraanKeluar().setVisible(true);  
        JOptionPane.showMessageDialog(null, "Selamat Datang" , "Menu Utama" , JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_kndraanKeluarActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_exitActionPerformed

    private void jexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexitActionPerformed
        // TODO add your handling code here:
         if
            (JOptionPane.showConfirmDialog(null, "Are you sure want to Exit ?","Confirm",
             JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION) {
            System.exit(0);
        }   
    }//GEN-LAST:event_jexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jexit;
    private javax.swing.JButton kndraanKeluar;
    private javax.swing.JButton kndraanMasuk;
    // End of variables declaration//GEN-END:variables
}
